FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    url(r'^(?P<an>\d+)?(/(?P<semaine>\d+))?$', views.edt, name="edt"),
    url(r'^tv/(?P<semaine>\d+)?(/(?P<an>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),
    url(r'^contact$', views.contact, name="contact"),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    url(r'^fetch_cours_pl/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pl, name="fetch_cours_pl"),
    url(r'^fetch_cours_pp/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pp, name="fetch_cours_pp"),
    url(r'^fetch_dispos/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_dispos, name="fetch_dispos"),
    url(r'^fetch_stype/$', views.fetch_stype, name="fetch_stype"),
    url(r'^fetch_decale/$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/$', views.fetch_bknews, name="fetch_bknews"),

    # from screen to db
    url(r'^change_edt/$', views.edt_changes, name="edt_changes"),
    url(r'^change_dispos/$', views.dispos_changes, name="dispos_changes"),
    url(r'^change_decale/$', views.decale_changes, name="decale_changes"),


    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/flopeditor/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from . import views
from django.conf.urls import url, include

app_name="flopeditor"

urlpatterns = [
    url(r'^test$', views.test, name="test"),
    url(r'^recup_cours/(?P<year>\d+)/(?P<week>\d+)$', views.recup_cours, name="recup_cours"),
    url(r'^(?P<year>\d+)/(?P<week>\d+)$', views.editor, name="editor"),
    url(r'^ajout_cours$', views.ajout_cours, name="ajout_cours"),
    url(r'^suppr_cours/(?P<year>\d+)/(?P<week>\d+)$', views.suppr_cours, name="suppr_cours")
]

FlOpEDT/flopeditor/models.py
from django.db import models

# Create your models here.

FlOpEDT/flopeditor/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from base.models import Course, Module, Group, TrainingProgramme, CourseType
from people.models import Tutor
from flopeditor.admin import CoursResourceTest
import re


def test(req):
    return render(req, 'flopeditor/test.html')

def editor(req, year, week):
    try:
        week = int(week)
        year = int(year)
    except ValueError:
        return HttpResponse("KO")


    return render(req, "flopeditor/flopeditor.html", {"year": year, "week": week})

def recup_cours(req, year, week):
    try:
        week = int(week)
        year = int(year)
    except ValueError:
        return HttpResponse("KO")

    dataset = CoursResourceTest() \
        .export(Course.objects \
                .filter(semaine=week,
                        an=year))

    return HttpResponse(dataset.csv, content_type='text/csv')

def ajout_cours(req):# module, group, prof, year, week_list
    if req.method != 'POST':
        return HttpResponse("KO")

    try:
        tab_week_str = req.POST["week_list"].split(',')
        tab_week = []
        for week_str in tab_week_str:
            tab_week.append(int(week_str))

        year = int(req.POST["year"])
    except ValueError:
        return HttpResponse("KO")

    mod = Module.objects.filter(abbrev = req.POST["module"]).first()
    prof = Tutor.objects.filter(username = req.POST["prof"]).first()
    group = Group.objects.filter(nom = req.POST["group"], train_prog = mod.train_prog ).first()


    if re.match("^CE$", req.POST["group"]):
        cType = "CM"
    elif re.match("^[1-4]$", req.POST["group"]):
        cType = "TD"
    elif re.match("^[1-4][AB]$", req.POST["group"]):
        cType = "TP"
    else:
        return HttpResponse("KO")

    courseType = CourseType.objects.get(name = cType)

    for week in tab_week:
        course = Course(tutor=prof, groupe=group, module=mod, semaine=week, an=year, type=courseType)
        course.save()

    return redirect("/editor/" + req.POST["year"] + "/" + week_str)

def suppr_cours(req, year, week):
    tab_id_str = req.POST["course_list"].split(',')
    for id_str in tab_id_str:
        Course.objects.get(id = int(id_str)).delete()

    return redirect("/editor/" + year + "/" + week)

FlOpEDT/flopeditor/templates/flopeditor/flopeditor.html
{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
{% load static %}
  <link rel="stylesheet" href="{% static "flopeditor/sidenav.css" %}"/>
  <link rel="stylesheet" href="{% static "base/better.css" %}"/>
  <script>
  var url_cours = "{% url "flopeditor:recup_cours" 0 0 %}";
  url_cours = url_cours.slice(0,-3);
  var year = {{year}};
  var week = {{week}};
  console.log(year);
  console.log(week);
  console.log(url_cours);
  </script>
  <script type="text/javascript" src="{% static 'flopeditor/printSVG.js' %}"></script>
  <script type="text/javascript" src="{% static 'flopeditor/editor.js' %}"></script>

  <div class="sidenav">
    <button class="accordion">Ajouter cours</button>
    <div class="panel">
      <form action="{% url 'flopeditor:ajout_cours' %}" method="post" >
        Semaine<br>
        <input type="text" name="week_list" placeholder="Ex: 38 ou 38,42,51">
        <br>Année<br>
        <input type="text" name="year"  placeholder="Ex: 2015">
        <br>Prof<br>
        <input type="text" name="prof" placeholder="Ex: PSO">
        <br>Group<br>
        <input type="text" name="group" placeholder="Ex: 3A">
        <br>Module<br>
        <input type="text" name="module" placeholder="Ex: IAP">
        <br><br>
        <input type="submit" value="Valider">
      </form>
    </div>

    <button class="accordion">Supprimer cours</button>
    <div class="panel">
      <form action="{% url 'flopeditor:suppr_cours' year week %}" method="post" >
        Cours<br>
        <input id="course_list" type="textarea" name="course_list" readonly>
        <br>
        <input type="submit" value="Valider">
      </form>
    </div>

    <script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight){
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
    </script>
  </div>
{% endblock %}

FlOpEDT/flopeditor/templates/flopeditor/test.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static "flopeditor/sidenav.css" %}"/>
<link rel="stylesheet" href="{% static "base/better.css" %}"/>



<script>
  var url_cours = "{% url "flopeditor:recup_cours" 0 0 %}";
  url_cours = url_cours.slice(0,-3);
</script>



<script type='text/javascript' src="{% static 'flopeditor/test.js' %}"></script>




<div class="sidenav">
  <a href="#">About</a>
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>

  <button class="accordion">Ajouter cours</button>
  <div class="panel">
    <form action="{% url 'flopeditor:ajout_cours' %}" method="post" >
      Semaine<br>
      <input type="text" name="week_list" placeholder="Ex: 38 ou 38,42,51">
      <br>Prof<br>
      <input type="text" name="prof" placeholder="Ex: PSO">
      <br>Group<br>
      <input type="text" name="group" placeholder="Ex: 3A">
      <br>Module<br>
      <input type="text" name="module" placeholder="Ex: IAP">
      <br><br>
      <input type="submit" value="Submit">
    </form>
  </div>

</div>




<div id="tools-main" style="padding:10px;">

    <h4>TESTTTTTTTTTTTTTTTTTTTTTTTTTTT</h4>



</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    }
  });
}
</script>
{% endblock %}